### ISSUE TITLE
What was wrong with the old android server?

### ISSUE THREAD

**Issue by s12227054** [Nomagno/NDS-NetworkedInput#2]

**Comment by Nomagno** [comment]
Hello and thanks for opening this issue! The old Android server is perfectly fine and I provide a binary now, however it does not really build, and even if it did, it's a Java implementation. 

Since I cannot build it, and I'm trying to promote use of the NDS-NetworkedInput C library, I think it's better suited to make one from scratch. I will however try my best to keep compatibility with the legacy version until it's ready, rest assured!
